### ISSUE TITLE
TypeError: '<' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by cliangyu** [AhmadQasim/Med-AL-SSL#15]
Active learning sampling error:
`Traceback (most recent call last):
  File "train.py", line 347, in <module>
    main(args=arguments)
  File "train.py", line 187, in main
    kwargs, current_labeled)
  File "/home/zongwei/liangyu/code/Med-AL-SSL/code/utils.py", line 471, in perform_sampling
    samples_indices)
  File "/home/zongwei/liangyu/code/Med-AL-SSL/code/utils.py", line 144, in postprocess_indices
    samples_indices = samples_indices[samples_indices < len(unlabeled_indices)]
TypeError: '<' not supported between instances of 'list' and 'int'`

**Comment by cliangyu** [comment]
`samples_indices = np.array(samples_indices)` solved the issue.
